cache:
    - "c:\\sr -> .appveyor.yml"

build: off

before_test:
    - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
    - 7z x stack.zip stack.exe
    - curl -oabc.exe http://www.eecs.berkeley.edu/~alanmi/abc/abc10216.exe
    - set "PATH=%PATH%;%cd%"

clone_folder: "c:\\project\\scenco"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
    - stack init
    - stack setup > nul
    - stack exec -- ghc --version
    - stack build
    - stack test
